#!/bin/bash
if ! [ "$(id -u)" = "0" ]; then
    echo "need to be root"
    exit 1
fi


if ! [ -d tftpboot ]; then
    echo "no tftpboot directory"
    exit 1
fi

if ! [ -d binary ]; then
    echo "no binary directory"
    exit 1
fi


rm /var/lib/tftpboot/* /freespace/paella/* -fr
mv binary/* /freespace/paella/
mv tftpboot/* /var/lib/tftpboot/
rmdir tftpboot
rmdir binary
