#!/bin/bash

# localpython will be the directory containing python modules and packages
# it will need to be exported as PYTHONPATH in your environment or .basrc
localpython=$HOME/local/python

# workspace is the parent path of where the subversion checkouts will be
workspace=$HOME/workspace

binpath=$HOME/bin


# these packages are absolutely necessary
depends="python-xml python-pycurl python-sqlite python-pgsql python-kde3
python-qtext libqt3-mt-psql python-apt python-pyparsing
python-cheetah python-kjbuckets"

depends=""
# you will need these if you wish to build paella debian packages
build_deps="build-essential cdbs devscripts python-docutils python-all-dev"


umlpackages=""
# if you already have these packages comment them out
#umlpackages="user-mode-linux uml-utilities debootstrap"


postgresql_packages=""
# uncomment below if you plan on running the postgresql server
# on this host.
#postgresql_packages="postgresql postgresql-contrib"


#extra="debconf-utils reiserfsprogs xfsprogs hdparm mdadm
#mkisofs gawk xxdiff xemacs21 kernel-package apache"
extra=""

debianlive="live-helper dosfstools memtest86+ parted squashfs-tools genext2fs mtd-tools syslinux uuid-runtime"

# you should not need to change anything below here

for directory in $localpython $workspace $binpath
  do
  echo checking $directory
  if ! [ -d $directory ]; then
      echo creating $directory
      mkdir -p $directory
  fi
  done


pushd $workspace
# checkout paella
if ! [ -d paella ]; then
    svn co svn://svn.berlios.de/paella/trunk paella
fi

# checkout useless
if ! [ -d useless ]; then
    svn co svn://svn.berlios.de/useless/trunk useless
fi
popd


pushd $localpython
if ! [ -L paella ]; then
    ln -s $workspace/paella/src/paella
fi
if ! [ -L useless ]; then
    ln -s $workspace/useless/useless
fi
popd


# here is how you can add the scripts to your path
# if you need to work from the working copy
pushd $binpath
#scripts="paella-management paella-make-base paella-kde-umlmanager"
scripts=""
for script in $scripts
  do
  echo checking script $script
  if ! [ -L $script ] ; then
      ln -s $workspace/paella/config/scripts/$script
  fi
  done
popd


#PACKAGES="$depends $build_deps $umlpackages $postgresql_packages $extra"
PACKAGES="$build_deps $debianlive"
echo "Cut and paste this command into the terminal to install the packages:"
echo

echo sudo apt-get install $PACKAGES
echo

echo "export PATH=$binpath:\$PATH" > paella_environment
echo "export PYTHONPATH=$localpython" >> paella_environment

echo add $binpath to your PATH, if not already there
echo add \"export PYTHONPATH=$localpython\" to your .bashrc file

echo "or source the paella_environment file that was just created in this directory"
echo before using paella.

cat <<EOF > ~/.screenrc
chdir workspace
screen -t local 0

chdir /freespace/live
screen -t live 1

chdir /freespace/debian
screen -t debian 2

chdir /freespace/paellalog
screen -t paellalog1 3

chdir /freespace/paellalog
screen -t paellalog2 4

screen -t root 5



EOF


# Install packages
echo "installing these packages: $PACKAGES"
sudo apt-get install $PACKAGES
echo "New Packages Installed."

