#!/bin/sh
set -e

in-target apt-get update
in-target apt-get -y dist-upgrade

echo "copying scripts to /usr/local/bin"
cp /cdrom/setup-paella-server /target/usr/local/bin
cp /cdrom/paella-user-quick-setup /target/usr/local/bin

echo "copying paella config files to /usr/local/share/paella"
cp -a /cdrom/paella /target/usr/local/share/
chmod -R +w /target/usr/local/share/paella

echo "copying logs to /target/root/"
cp -a /var/log  /target/root/install-logs
cp -a /var/lib/preseed /target/root/install-preseed
