Document: repserve
Title: Debian repserve Manual
Author: <insert document author here>
Abstract: This manual describes what repserve is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/repserve/repserve.sgml.gz

Format: postscript
Files: /usr/share/doc/repserve/repserve.ps.gz

Format: text
Files: /usr/share/doc/repserve/repserve.text.gz

Format: HTML
Index: /usr/share/doc/repserve/html/index.html
Files: /usr/share/doc/repserve/html/*.html


